#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

j=0

while [ $j -le 12 ]
do
  echo "Hour: $j"
  mins=1
  while [ $mins -le 59 ]
  do
    echo "$mins"
    (( mins++ ))
  done
  (( j++ ))
done

